import Head from "next/head";
import { Inter } from "next/font/google";
import Fuse from "fuse.js";
import styles from "@/styles/Home.module.scss";
import { build } from "search-params";
import { useEffect, useMemo, useState } from "react";
import classNames from "classnames";
import { sortBy, uniqBy } from "lodash";

const inter = Inter({ subsets: ["latin"] });

const maleEngland = [
  { key: "fid#4", name: "gender", values: [{ name: "Male", key: "Male" }] },
  { key: "fid#12", name: "age", values: [{ name: "Any Age", key: "Any Age" }] },
  {
    key: "fid#16",
    name: "country",
    values: [{ name: "England", key: "England" }],
  },
];

const types = ["Individual", "Pairs", "Team"];

const fetcher = (offset, opts) => {
  const params = build({ offset, filters: JSON.stringify(opts) });
  return fetch(["/api/search", params].join("?")).then((r) => r.json());
};

const date = new Date();
const userTimezoneOffset = Math.abs(date.getTimezoneOffset() * 60000);

const getPoint = (key, result, format = true) => {
  const point =
    result.dataPoints.find((point) => point.key === key)?.value ?? "";

  if (key === "Date" && point && format) {
    return new Date(point * 1000 + userTimezoneOffset).toDateString();
  }
  return point;
};

const columns = [
  "Golf Club",
  "Type",
  "County",
  "Format",
  "Entry Fee",
  "Date",
  "Day",
  "Holes",
];

export default function Home() {
  const [results, setResults] = useState([]);
  const [searchResults, setSearchResults] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [currentType, setCurrentType] = useState("Pairs");
  const [search, setSearch] = useState("");
  const [sort, setSort] = useState("Date");
  const hasResults = !isLoading && results && results.length > 0;

  useEffect(() => {
    setIsLoading(true);

    const getResults = async () => {
      const fetchOptions = [
        {
          key: "fid#5",
          name: "type",
          values: [{ name: currentType, key: currentType }],
        },
        ...maleEngland,
      ];

      let offset = 0;
      let data = await fetcher(offset, fetchOptions);

      setResults([...data.results]);
      while (data && data.totalResults && data.totalResults > offset) {
        offset = offset + 24;
        if (offset > data.totalResults) {
          offset = data.totalResults;
        }
        data = await fetcher(offset, fetchOptions);
        if (data.results.length > 0) {
          setResults((r) => uniqBy([...r, ...data.results], "link"));
        }
      }
    };

    setResults([]);
    getResults().then(() => {
      setIsLoading(false);
    });
  }, [currentType]);

  const fuse = useMemo(
    () =>
      new Fuse(results, {
        threshold: 0.0,
        keys: ["dataPoints.value"],
        findAllMatches: true,
        ignoreLocation: true,
      }),
    [results]
  );

  useEffect(() => {
    const searchResult = search
      ? fuse.search(search)?.map(({ item }) => item) ?? results
      : results;

    const sorted = sortBy(searchResult, (result) =>
      getPoint(sort, result, false)
    );

    setSearchResults(sorted);
  }, [fuse, search, results, sort]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classNames(styles.main, inter.className)}>
        <nav>
          {types.map((type) => (
            <button
              className={classNames({ active: type === currentType })}
              key={type}
              onClick={() => setCurrentType(type)}
            >
              {type}
            </button>
          ))}
        </nav>
        <br />
        <form>
          <label>Search</label>
          <br />
          <input
            type="search"
            onInput={(e) => setSearch(e.target.value)}
            value={search}
          />
        </form>
        <br />
        <h1>Results: {searchResults.length}</h1>
        {isLoading && "Loading..."}
        {hasResults && (
          <table>
            <thead>
              <tr>
                {columns.map((col) => (
                  <th
                    className={classNames({ active: sort === col })}
                    key={col}
                    onClick={() => setSort(col)}
                  >
                    {col}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {searchResults.map((result, resultIndex) => (
                <tr key={result.name + result.content + resultIndex}>
                  {columns.map((col) => (
                    <td key={col}>{getPoint(col, result)}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </main>
    </>
  );
}
